apiVersion: apps/v1
kind: Deployment
metadata:
  name: protousercore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protousercore
  template:
    metadata:
      labels:
        app: protousercore
    spec:
      containers:
      - name: protousercore
        image: protousercore          
        imagePullPolicy: Never        
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: protousercore
spec:
  selector:
    app: protousercore
  ports:
    - port: 50051
      targetPort: 50051
